### ISSUE TITLE
Problem 2 15 - phpunit/php-file-iterator is locked to version

### ISSUE THREAD

**Issue by shinqy** [naventum/naventum#21]
PHP version not compatible with PHPunit

`Problem 2 15 - phpunit/php-file-iterator is locked to version dev-main and an update of this package was not requested. 16 - phpunit/php-file-iterator dev-main requires php >=8.1 -> your php version (7.3.33) does not satisfy that requirement. 17 Error: Your lock file does not contain a compatible set of packages. Please run composer update.`

Naventum requires PHP :

```
 "php": "^7.3|^8.0",
```

PHPunit required PHP :

```
     "php": ">=8.1",
     "dev-main": "10.0-dev"
```

**Comment by shinqy** [comment]
please check this problem

 Problem 1
    - Root composer.json requires phpunit/phpunit 7.2.3 -> satisfiable by phpunit/phpunit[7.2.3].
    - phpunit/phpunit 7.2.3 requires php ^7.1 -> your php version (8.0.18) does not satisfy that requirement.

**Comment by rizkytegar** [comment]
delete "phpunit/phpunit": "9.5.20" in composer.json

please try

```
composer update
```

and

```
composer require phpunit/phpunit --prefer-dist
```

**Comment by shinqy** [comment]
> delete "phpunit/phpunit": "9.5.20" in composer.json
> 
> please try
> 
> ```
> composer update
> ```
> 
> and
> 
> ```
> composer require phpunit/phpunit --prefer-dist
> ```

--prefer-dist is unstable for this project

**Comment by ryotwell** [comment]
If you are using php 8, use the 8.1 version, 

See here phpunit/php-file-iterator requires php 8.1

https://github.com/sebastianbergmann/php-file-iterator
